import React from 'react'
import Table from 'react-bootstrap/esm/Table'
import Modal from 'react-bootstrap/Modal'
import '../Styling/PaymentRequest.css'





const PaymentRequestModal = ({paymentRequestInfo,showModal,hideModal}) => {
  return (

    <Modal
        size="lg"
        show={showModal}
        onHide={hideModal}
        aria-labelledby="example-modal-sizes-title-lg"
      >
        <Modal.Header closeButton>
        <Modal.Title className='modal-tile'>
            <h4 className='text-center'>ZanaAfrica</h4>
        </Modal.Title>
        </Modal.Header>

        {/* Info */}
        <Modal.Body>
            <Table>
                <tbody>
                    <tr>
                        <td className='titles'>PAYMENT REQUEST FORM</td>
                        <td className='titles'>PV reference number:</td>
                    </tr>
                    <tr>
                        <td className='titles'>Generated by:</td>
                        <td>name of User</td>
                        <td></td>
                        <td className='titles'>Payee</td>
                        <td>p</td>

                        <td></td>
                        <td></td>

                    </tr>

                    <tr>
                        <td>Budget holder:</td>
                        <td>bh</td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>

            </Table>
        </Modal.Body>
    </Modal>
  )
}

export default PaymentRequestModal